name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev

      - name: Install Buildozer
        run: |
          pip3 install --user --upgrade pip
          pip3 install --user --upgrade buildozer cython

      - name: Manual SDK Setup
        run: |
          # Создаем структуру папок, которую ищет Buildozer
          mkdir -p /home/runner/.buildozer/android/platform/android-sdk/build-tools/33.0.0
          
          # Скачиваем Build-Tools 33.0.0 напрямую с серверов Google
          wget -q https://dl.google.com/android/repository/build-tools_r33.0.0-linux.zip
          unzip -q build-tools_r33.0.0-linux.zip -d /tmp/bt
          mv /tmp/bt/android-13/* /home/runner/.buildozer/android/platform/android-sdk/build-tools/33.0.0/
          
          # Устанавливаем права
          chmod +x /home/runner/.buildozer/android/platform/android-sdk/build-tools/33.0.0/aidl

      - name: Build APK
        env:
          BUILDOZER_HOME: /home/runner/.buildozer
        run: |
          export PATH=$PATH:~/.local/bin
          # Запуск сборки
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AngerAI-APK
          path: bin/*.apk
