name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev

      - name: Setup Buildozer
        run: |
          pip3 install --user --upgrade pip
          pip3 install --user --upgrade buildozer
          pip3 install --user --upgrade cython

      - name: Accept Licenses and Prepare SDK
        run: |
          # Создаем структуру папок для SDK
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          # Принимаем все лицензии принудительно через 'yes'
          # Используем путь к sdkmanager, который устанавливает Buildozer
          yes | sdkmanager --licenses || true
          yes | sdkmanager --update || true

      - name: Build with Buildozer
        run: |
          export PATH=$PATH:~/.local/bin
          # Запуск сборки
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AngerAI-APK
          path: bin/*.apk
          
