name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev
          pip3 install --user --upgrade pip
          pip3 install --user --upgrade buildozer cython

      - name: Setup SDK & Licenses
        run: |
          # Устанавливаем Android SDK через командную строку
          # Это создает правильную структуру, которую Buildozer сам распознает
          export ANDROID_HOME=/home/runner/android-sdk
          mkdir -p $ANDROID_HOME/licenses
          echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > $ANDROID_HOME/licenses/android-sdk-license
          echo -e "\n84831b9409646a918e30573bab4c9c91346d8613" >> $ANDROID_HOME/licenses/android-sdk-license
          
          # Указываем Buildozer-у где искать SDK
          echo "android.sdk_path = $ANDROID_HOME" >> buildozer.spec

      - name: Build APK
        run: |
          export PATH=$PATH:~/.local/bin
          # Запуск сборки: buildozer сам скачает build-tools, 
          # если мы правильно указали путь к SDK
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AngerAI-APK
          path: bin/*.apk
